title: "リーンスタートアップ 読了メモ"
summary: "名著、[リーンスタートアップ](https://bookplus.nikkei.com/atcl/catalog/12/P48970/)を読んだときのメモ"
topics: ["リーンスタートアップ"]
published: false
price: 0
chapters:
  - c0.overall
  - c1
  - c2
  - c3
